application: beers
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  
- url: /api/.*
  script: _go_app
  login: required
  auth_fail_action: unauthorized
  
- url: /beers
  script: _go_app
  login: required
